anchor_version = "0.24.2"

[workspace]
members = ["programs/locking", "programs/staking", "programs/farming"]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
locking = "DNTDdX18wZCfRWzB6auDDi8CqX3TQTLSZGd8LwTpusNL"
staking = "9D9cdG8WV336qsjWe6PeMkqcsBmAWTZhddQgTfQrsHqc"
farming = "DUALszVmfxqFLXDQpkrf8S6qHNxjqeBdDnqne74Bwhvw"
