anchor_version = "0.24.2"

[workspace]
members = ["programs/staking", "programs/single-farming", "programs/dual-farming"]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
staking = "FFkqjHsFZS3MaUELNrz4TMNo1pz5nE3sBShjuMiSy1Pz"
single_farming = "Dev9TukuTHwNmYm2NUcXQ9iuNL8UrP3TnZCj1Y7UjV18"
dual_farming = "AXFHikQNKk2zgiss9USaUVccLt4TSqmXBLEkZZ6GhojH"
