[package]
name = "farming"
version = "0.2.2"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "farming"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
devnet = []
verbose = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
spl-math = { version = "0.3.0", features = ["no-entrypoint"] }
