name: Rust

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  SOLANA_CLI_VERSION: 1.9.19
  NODE_VERSION: 16.15.0

jobs:
  setup-anchor-cli:
    name: Setup Anchor cli
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup/
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: ./.github/actions/setup-ts/
      - uses: ./.github/actions/git-diff/
  test-programs:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    needs: setup-anchor-cli
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: anchor-build
    - name: Cargo test
      run: cargo test
    - name: Run anchor test
      run: anchor test -- --features dev
    - name: Cargo fmt
      run: cargo fmt